# Generated by Django 5.2.9 on 2025-12-07 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='e.g., "John 3:16"', max_length=100)),
                ('translation', models.CharField(help_text='e.g., "ESV", "NIV"', max_length=20)),
                ('text_content', models.TextField(help_text='The actual verse text')),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('in_progress', 'In Progress'), ('memorized', 'Memorized')], default='upcoming', help_text='Current memorization status', max_length=20)),
                ('hidden_indices', models.JSONField(blank=True, default=list, help_text='List of integers representing hidden word indices')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'verses',
                'ordering': ['-created_at'],
            },
        ),
    ]
